### ISSUE TITLE
Action Reference

### ISSUE THREAD

**Issue by jardicc** [JavierAroche/descriptor-info#1]
this line:
`descProperties.reference = executeActionGet( descProperties.value );`
fails quite offten, but you can't see it because it is in try{} block.

There is some more info you can get from action reference no matter if problematic line works or not.

- getDesiredClass()
- getForm()
and then depends on reference form
- getEnumeratedType() + getEnumeratedValue()
- or something else

I am using your tool for events analyzing. And structure is very similar to ScriptListener code except action references. The benefit is that I don't need read from disk and parse text file. And I also can access values like: 
`if(desc.to.fontCaps == "normal")
{//do something}`

And with extended info, I could run same event again with a bit different parameter value. If I could write code which can rebuild Action Descriptor like JAM framework.

Non-extended for `arguments[0]`
```
{
    "null": {
        "typename": "ActionReference"
    },
    "to": {
        "textOverrideFeatureName": 808465713,
        "typeStyleOperationType": 3,
        "fontCaps": "normal"
    }
}
```
`arguments[1]` contains eventID "setD"

Extended
```
{
    "null": {
        "stringID": "null",
        "charID": "null",
        "id": 1853189228,
        "key": 0,
        "type": "DescValueType.REFERENCETYPE",
        "value": {
            "typename": "ActionReference"
        }
    },
    "to": {
        "stringID": "to",
        "charID": "T   ",
        "id": 1411391520,
        "key": 1,
        "type": "DescValueType.OBJECTTYPE",
        "value": {
            "count": 3,
            "typename": "ActionDescriptor"
        },
        "object": {
            "textOverrideFeatureName": {
                "stringID": "textOverrideFeatureName",
                "charID": "",
                "id": 3837,
                "key": 0,
                "type": "DescValueType.INTEGERTYPE",
                "value": 808465713
            },
            "typeStyleOperationType": {
                "stringID": "typeStyleOperationType",
                "charID": "",
                "id": 1366,
                "key": 1,
                "type": "DescValueType.INTEGERTYPE",
                "value": 3
            },
            "fontCaps": {
                "stringID": "fontCaps",
                "charID": "",
                "id": 1329,
                "key": 2,
                "type": "DescValueType.ENUMERATEDTYPE",
                "value": "allCaps",
                "enumerationType": "fontCaps"
            }
        }
    }
}
```

Script Listener
```
var idsetd = charIDToTypeID( "setd" );
    var desc1952 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref582 = new ActionReference();
        var idPrpr = charIDToTypeID( "Prpr" );
        var idTxtS = charIDToTypeID( "TxtS" );
        ref582.putProperty( idPrpr, idTxtS );
        var idTxLr = charIDToTypeID( "TxLr" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref582.putEnumerated( idTxLr, idOrdn, idTrgt );
    desc1952.putReference( idnull, ref582 );
    var idT = charIDToTypeID( "T   " );
        var desc1953 = new ActionDescriptor();
        var idtextOverrideFeatureName = stringIDToTypeID( "textOverrideFeatureName" );
        desc1953.putInteger( idtextOverrideFeatureName, 808465713 );
        var idtypeStyleOperationType = stringIDToTypeID( "typeStyleOperationType" );
        desc1953.putInteger( idtypeStyleOperationType, 3 );
        var idfontCaps = stringIDToTypeID( "fontCaps" );
        var idfontCaps = stringIDToTypeID( "fontCaps" );
        var idallCaps = stringIDToTypeID( "allCaps" );
        desc1953.putEnumerated( idfontCaps, idfontCaps, idallCaps );
    var idTxtS = charIDToTypeID( "TxtS" );
    desc1952.putObject( idT, idTxtS, desc1953 );
executeAction( idsetd, desc1952, DialogModes.NO );

```

**Comment by JavierAroche** [comment]
> this line:
> descProperties.reference = executeActionGet( descProperties.value );
> fails quite offten, but you can't see it because it is in try{} block.

Hey @jardicc, I've been doing some tests, but I haven't caught any errors on that line. You're correct, it's in a try / catch block, but the catch will send the error to the console, specifying which stringID it failed on. 
```
} catch(err) {
    $.writeln('error: ' + descStringID + ' - ' + err);
}
```
It would be great if you could show me the code you're running when descriptor-info fails.

> There is some more info you can get from action reference no matter if problematic line works or not.

Yes, I'm aware of this. Unfortunately I don't really know what's inside any action reference, that's why I simply return the reference object and not its contents. That way you can get those properties, if you need them. 

If the reference flag is set to true, it will run an executeActionGet on the action reference, otherwise it will return it as is. See [README](https://github.com/JavierAroche/descriptor-info#getproperties) for the reference flag (Default = false).

> I am using your tool for events analyzing. And structure is very similar to ScriptListener code except action references. The benefit is that I don't need read from disk and parse text file.

Yes, this is why I wrote this! :) The structure of the returned object won't always be the most optimal, but that's how Photoshop's Action Descriptors are structured.

> If I could write code which can rebuild Action Descriptor like JAM framework.

I agree that that would be pretty cool. At the moment descriptor-info is a getter, not a setter (hence the "info" in the title). There's a good amount of logic that would have to go into this to make it a setter. I will definitely explore it though.

**Comment by jardicc** [comment]
I traced script and it never goes into catch block.
add this on the top of your script `$.level = 1;` and open Extension Script Toolkit
This will stop script in case of error and you can trace script from error point and see variables even if error is in "try" block.

I use script event manager and I set trigerring script for `All ` events.
And except JSON code and ActionDescriptor tool I have this code inside.
Then if I change tool in PS toolbar it shows me that action reference failed.


```
var test = "";
var descFlags = {
    reference : true,
    extended : true
};

var descriptorInfo = new DescriptorInfo();
var desc = arguments[0];
var descObject = descriptorInfo.getProperties( desc, descFlags);
test = test + JSON.stringify(descObject, null, 4);
test = test + "\n";
saveTxt (test);

function saveTxt(txt)
{
    var saveFile = File('~/desktop/ScriptListenerJSON.json');

    if(saveFile.exists)  
        saveFile.remove();

    saveFile.encoding = "UTF8";
    saveFile.open("e", "TEXT", "????");
    saveFile.writeln(txt);
    saveFile.close();
}
```


I will try extend your script to get more info from action script reference in order to have same data structure in JSON and Script Listener code. Anyway my code skills are not as good as you and my code can be a bit dirty :-D

**Comment by jardicc** [comment]
I am working on improvements:
Now I am able to get some more info from events actionReference arguments.
This code is generated if I click on cropTool. Without my extension you are unable to read which tool was activated. Still missing some info and needs polish but it is on the good way.

```
{
    "select": {
        "null": {
            "stringID": "null",
            "charID": "null",
            "id": 1853189228,
            "key": 0,
            "type": "DescValueType.REFERENCETYPE",
            "value": {
                "typename": "ActionReference"
            },
            "actionReference": {  // <--- THIS IS NEW!!!
                "stringID": "cropTool",
                "charID": "",
                "id": 243,
                "type": "ReferenceFormType.CLASSTYPE",
                "value": 243
            }
        },
        "dontRecord": {
            "stringID": "dontRecord",
            "charID": "",
            "id": 3609,
            "key": 1,
            "type": "DescValueType.BOOLEANTYPE",
            "value": true
        },
        "forceNotify": {
            "stringID": "forceNotify",
            "charID": "",
            "id": 3305,
            "key": 2,
            "type": "DescValueType.BOOLEANTYPE",
            "value": true
        }
    }
}
```

next example:
```
{
    "select": {
        "null": {
            "stringID": "null",
            "charID": "null",
            "id": 1853189228,
            "key": 0,
            "type": "DescValueType.REFERENCETYPE",
            "value": {
                "typename": "ActionReference"
            },
            "actionReference": { // <--- This is new
                "stringID": "layer",
                "charID": "Lyr ",
                "id": 1283027488,
                "type": "ReferenceFormType.NAME",
                "value": "test lorem ipsum"
            }
        },
        "makeVisible": {
            "stringID": "makeVisible",
            "charID": "MkVs",
            "id": 1298880115,
            "key": 1,
            "type": "DescValueType.BOOLEANTYPE",
            "value": false
        },
        "layerID": {
            "stringID": "layerID",
            "charID": "LyrI",
            "id": 1283027529,
            "key": 2,
            "type": "DescValueType.LISTTYPE",
            "value": {
                "count": 1,
                "typename": "ActionList"
            },
            "list": [
                16
            ]
        }
    }
}
```

Now I am able to read that I selected layer and name of layer by default.

**Comment by JavierAroche** [comment]
That's awesome @jardicc! Feel free to make a pull request with your updated code, it'd be super helpful for whoever is using this script! :)

**Comment by jardicc** [comment]
How can I do pull request. I never did it. I tried to look how I could, but I couldn't figure it out.
You will also need polish my code to remain some order and consistency.

I am finnaly able to get same info from arguments like from script listener. (Probably)
Examples of new info from reference.
```
...
"null": {
            "stringID": "null",
            "charID": "null",
            "id": 1853189228,
            "key": 0,
            "type": "DescValueType.REFERENCETYPE",
            "value": {
                "typename": "ActionReference"
            },
            "actionReference": {
                "stringID": "layer",
                "charID": "Lyr ",
                "id": 1283027488,
                "type": "ReferenceFormType.ENUMERATED",
                "value": "targetEnum"
            },
            "reference": {
                "count": 41,
                "typename": "ActionDescriptor"
            }
        }
...
```

```
...
"null": {
            "stringID": "null",
            "charID": "null",
            "id": 1853189228,
            "key": 0,
            "type": "DescValueType.REFERENCETYPE",
            "value": {
                "typename": "ActionReference"
            },
            "actionReference": {
                "stringID": "layer",
                "charID": "Lyr ",
                "id": 1283027488,
                "type": "ReferenceFormType.NAME",
                "value": "UX Project Checklist"
            },
            "reference": {
                "count": 41,
                "typename": "ActionDescriptor"
            }
        }
...
```

```
...
"null": {
            "stringID": "null",
            "charID": "null",
            "id": 1853189228,
            "key": 0,
            "type": "DescValueType.REFERENCETYPE",
            "value": {
                "typename": "ActionReference"
            },
            "actionReference": { // <--- usual action reference
                "stringID": "property",
                "charID": "Prpr",
                "id": 1349677170,
                "type": "ReferenceFormType.PROPERTY",
                "value": "textStyle"
            },
            "actionReferenceGetContainer": { // <--- sometimes is some info wraped into .getContainer()
                "stringID": "textLayer",
                "charID": "TxLr",
                "id": 1417170034,
                "type": "ReferenceFormType.ENUMERATED",
                "value": "targetEnum"
            },
            "referenceGetContainer": { // <--- sometimes you must using descProperties.value.getContainer() instead descProperties.value and maybe sometimes both
                "count": 43,
                "typename": "ActionDescriptor"
            }
        }
...
```

**Comment by JavierAroche** [comment]
Yeah that's the problem with references, you never really know what's inside, so you have to test different things like .getContainer().

> How can I do pull request. I never did it. I tried to look how I could, but I couldn't figure it out.

At the top of this page, you will see 3 buttons on the right hand side: Watch / Star / Fork. Click on Fork. This will clone this project into your repositories. You can commit your changes, and when it's ready, just make a pull request so I can merge both our projects.

You can read a little bit more about it here:
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by jardicc** [comment]
You should have pull request from me.

You will need modify non-extended mode. Now there may be some IDs numbers in value instead meaningfull names.

**Comment by jardicc** [comment]
I figured out what means .getContainer() method in references.

Sometimes reference targets certain properties in layer/document/channel ect. 
So you get descriptor only for this property. getContainer() removes this property targeting and you get descriptor for whole layer/document/channel ect.

**Comment by JavierAroche** [comment]
These are some of the errors I was talking about in https://github.com/JavierAroche/descriptor-info/issues/8#issuecomment-299674204, when reading references:

> Unable to run executeActionGet from value: undefined - Error: General Photoshop error occurred. This functionality may not be available in this version of Photoshop.
> - Could not complete your request because of a program error.

> Unable to run executeActionGet from container: undefined - IOError: General Photoshop error occurred. This functionality may not be available in this version of Photoshop.
> - Could not complete your request because of a disk error.

Do you think the disk error is due to an endless recursive reference? I've struggled with some of those in the past.

**Comment by JavierAroche** [comment]
This has been merged in https://github.com/JavierAroche/descriptor-info/pull/12
