### ISSUE TITLE
Raw format problem

### ISSUE THREAD

**Issue by jardicc** [JavierAroche/descriptor-info#4]
I have JSON arguments listener based on this tool and I noticed some strange behavior.

When worked in Photoshop, there was a lag. My .log file jumped from 150Kb size to 68MB size.
I saw that there was 25 000 000 characters in "Raw data type" value.
Photoshop then began acting strangely.

I'm not sure exactly what happened. But I think we could reduce the length of the value to 10 000 characters by default. And if we want more then we would use the flag.

If it occurs again, I will tell you.

**Comment by jardicc** [comment]
I suggest this solution:
```
 case 'DescValueType.RAWTYPE':  
            var rawLen = theDesc.getData( position ).length;
            if( rawLen > 1000){
                return "To much long ("+rawLen+" characters) : "+theDesc.getData( position ).substring(0, 1000);
            }
            return theDesc.getData( position );
            break;
```

It works good for me. We could have flag in settings. Something like "rawLengthProtection: 1000"

**Comment by JavierAroche** [comment]
We now have a maxRawLimit flag! 
https://github.com/JavierAroche/descriptor-info/commit/f29afad0a2ca401de6195fd296fa182d46e1584d

This will be included in the next release
