### ISSUE TITLE
Script gets stuck when analyzing 3D layer

### ISSUE THREAD

**Issue by jardicc** [JavierAroche/descriptor-info#7]
Script gets stuck when analyzing 3D layer. Probably because there is huge amount of data or maybe very long RAW value somewhere.

**Comment by jardicc** [comment]
Solved. It's because RAW values are too long: https://github.com/JavierAroche/descriptor-info/issues/4#issuecomment-299644425

**Comment by JavierAroche** [comment]
Solved https://github.com/JavierAroche/descriptor-info/issues/4
